import = ["/home/lxm/.config/alacritty/alacritty-theme/themes/github_dark.toml"]

[env]
TERM = "xterm"

[font]
size = 12.0

[window]
opacity = 0.5

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 16
y = 16
