#! /bin/sh

export HELLO=hello
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx

# pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4

# 配置
bspc config border_width         0
bspc config window_gap           8
# bspc config top_padding          30
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# 规则
bspc rule -a 'Thunar' state=floating
bspc rule -a 'Pavucontrol' state=floating
bspc rule -a 'Blueman-manager' state=floating
bspc rule -a 'feh' state=floating
bspc rule -a 'Bytedance-feishu':*:* state=floating

# 自定义进程
# xrandr --output eDP-1 --auto
feh --bg-fill $HOME/workspace/doc/arch/wallpaper/backiee-125928-landscape.jpg
pkill -9 -f picom
pkill -9 -f fcitx5
pkill -9 -f sxhkd
polybar-msg cmd quit
pkill -9 -f plank
picom &
fcitx5 &
sxhkd &
polybar &
plank &


# 提升Polybar和Plank的层级
# https://www.reddit.com/r/bspwm/comments/gb25gx/it_is_possible_to_raise_polybar_to_be_above_all/
bspc subscribe node_add | while read -r event; do
    xdo raise -N Polybar
    xdo raise -N Plank
done &
bspc subscribe node_state | while read -r event; do
    if echo $event | grep 'fullscreen on' > /dev/null; then
        xdo lower -N Polybar
        xdo lower -N Plank
    elif echo $event | grep 'fullscreen off' > /dev/null; then
        xdo raise -N Polybar
        xdo raise -N Plank
    fi
done &